pr: none
trigger:   none

parameters:
- name: projectType
  displayName: Select Project
  type: string
  default: sales
  values:
  - sales
  - member

pool:
  vmImage: windows-latest

stages:
  - stage: 
    jobs:
      - job: 
        steps:
          # - task: PowerShell@2
          #   inputs:
          #     filePath: '$(system.defaultworkingdirectory)/Src/ScanMRCCore/test.ps1'
          #   condition: eq('${{ parameters.projectType }}', 'sales')
          # - task: PowerShell@2
          #   inputs:
          #     filePath: '$(system.defaultworkingdirectory)/Src1/ScanMRCCore/test.ps1'
          #   condition: eq('${{ parameters.projectType }}', 'member')

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)/Src'
              Contents: '**'
              TargetFolder: '$(Agent.TempDirectory)/Src'
              CleanTargetFolder: true
              OverWrite: true
            condition: eq('${{ parameters.projectType }}', 'sales')
          
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)/Src1'
              Contents: '**'
              TargetFolder: '$(Agent.TempDirectory)/Src1'
              CleanTargetFolder: true
              OverWrite: true
            condition: eq('${{ parameters.projectType }}', 'Member')     

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)/Test'
              Contents: '**'
              TargetFolder: '$(Agent.TempDirectory)/Test'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'tree "$(Agent.TempDirectory)" /F'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Agent.TempDirectory)'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              artifact: 'build'
              publishLocation: 'pipeline'